Search.appendIndex(
    [
                {
            "fqsen": "\\BULK_PRODUCT_IMPORT_PLUGIN_PATH",
            "name": "BULK_PRODUCT_IMPORT_PLUGIN_PATH",
            "summary": "",
            "url": "namespaces/default.html#constant_BULK_PRODUCT_IMPORT_PLUGIN_PATH"
        },                {
            "fqsen": "\\BULK_PRODUCT_IMPORT_PLUGIN_URL",
            "name": "BULK_PRODUCT_IMPORT_PLUGIN_URL",
            "summary": "",
            "url": "namespaces/default.html#constant_BULK_PRODUCT_IMPORT_PLUGIN_URL"
        },                {
            "fqsen": "\\BULK_PRODUCT_IMPORT_ASSETS_PATH",
            "name": "BULK_PRODUCT_IMPORT_ASSETS_PATH",
            "summary": "",
            "url": "namespaces/default.html#constant_BULK_PRODUCT_IMPORT_ASSETS_PATH"
        },                {
            "fqsen": "\\bulk_product_import_plugin_load_textdomain\u0028\u0029",
            "name": "bulk_product_import_plugin_load_textdomain",
            "summary": "Load\u0020plugin\u0020text\u0020domain\u0020for\u0020internationalization.",
            "url": "namespaces/default.html#function_bulk_product_import_plugin_load_textdomain"
        },                {
            "fqsen": "\\bulk_product_import_get_theme_instance\u0028\u0029",
            "name": "bulk_product_import_get_theme_instance",
            "summary": "",
            "url": "namespaces/default.html#function_bulk_product_import_get_theme_instance"
        },                {
            "fqsen": "\\bpi_add_settings_link\u0028\u0029",
            "name": "bpi_add_settings_link",
            "summary": "",
            "url": "namespaces/default.html#function_bpi_add_settings_link"
        },                {
            "fqsen": "\\BULK_IMPORT\\Inc\\Admin_Menu",
            "name": "Admin_Menu",
            "summary": "Class\u0020Admin_Menu",
            "url": "classes/BULK-IMPORT-Inc-Admin-Menu.html"
        },                {
            "fqsen": "\\BULK_IMPORT\\Inc\\Admin_Menu\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/BULK-IMPORT-Inc-Admin-Menu.html#method___construct"
        },                {
            "fqsen": "\\BULK_IMPORT\\Inc\\Admin_Menu\u003A\u003Asetup_hooks\u0028\u0029",
            "name": "setup_hooks",
            "summary": "Setup\u0020the\u0020hooks.",
            "url": "classes/BULK-IMPORT-Inc-Admin-Menu.html#method_setup_hooks"
        },                {
            "fqsen": "\\BULK_IMPORT\\Inc\\Admin_Menu\u003A\u003Aregister_admin_menu\u0028\u0029",
            "name": "register_admin_menu",
            "summary": "Register\u0020the\u0020main\u0020admin\u0020menu.",
            "url": "classes/BULK-IMPORT-Inc-Admin-Menu.html#method_register_admin_menu"
        },                {
            "fqsen": "\\BULK_IMPORT\\Inc\\Admin_Menu\u003A\u003Aregister_csv_import_menu\u0028\u0029",
            "name": "register_csv_import_menu",
            "summary": "Register\u0020the\u0020CSV\u0020Import\u0020submenu.",
            "url": "classes/BULK-IMPORT-Inc-Admin-Menu.html#method_register_csv_import_menu"
        },                {
            "fqsen": "\\BULK_IMPORT\\Inc\\Admin_Menu\u003A\u003Aregister_sheet_import_menu\u0028\u0029",
            "name": "register_sheet_import_menu",
            "summary": "Register\u0020the\u0020Sheet\u0020Import\u0020submenu.",
            "url": "classes/BULK-IMPORT-Inc-Admin-Menu.html#method_register_sheet_import_menu"
        },                {
            "fqsen": "\\BULK_IMPORT\\Inc\\Admin_Menu\u003A\u003Abulk_product_import_page_html\u0028\u0029",
            "name": "bulk_product_import_page_html",
            "summary": "Render\u0020the\u0020main\u0020admin\u0020menu\u0020page.",
            "url": "classes/BULK-IMPORT-Inc-Admin-Menu.html#method_bulk_product_import_page_html"
        },                {
            "fqsen": "\\BULK_IMPORT\\Inc\\Admin_Menu\u003A\u003Abulk_product_csv_import_page_html\u0028\u0029",
            "name": "bulk_product_csv_import_page_html",
            "summary": "",
            "url": "classes/BULK-IMPORT-Inc-Admin-Menu.html#method_bulk_product_csv_import_page_html"
        },                {
            "fqsen": "\\BULK_IMPORT\\Inc\\Admin_Menu\u003A\u003Abulk_product_sheet_import_page_html\u0028\u0029",
            "name": "bulk_product_sheet_import_page_html",
            "summary": "",
            "url": "classes/BULK-IMPORT-Inc-Admin-Menu.html#method_bulk_product_sheet_import_page_html"
        },                {
            "fqsen": "\\BULK_IMPORT\\Inc\\Admin_Menu\u003A\u003Asave_client_credentials\u0028\u0029",
            "name": "save_client_credentials",
            "summary": "Save\u0020the\u0020client\u0020credentials\u0020via\u0020AJAX.",
            "url": "classes/BULK-IMPORT-Inc-Admin-Menu.html#method_save_client_credentials"
        },                {
            "fqsen": "\\BULK_IMPORT\\Inc\\Admin_Menu\u003A\u003Asave_table_prefix\u0028\u0029",
            "name": "save_table_prefix",
            "summary": "Save\u0020the\u0020table\u0020prefix\u0020via\u0020AJAX.",
            "url": "classes/BULK-IMPORT-Inc-Admin-Menu.html#method_save_table_prefix"
        },                {
            "fqsen": "\\BULK_IMPORT\\Inc\\Admin_Menu\u003A\u003Asave_profit_percentage_callback\u0028\u0029",
            "name": "save_profit_percentage_callback",
            "summary": "Save\u0020the\u0020profit\u0020percentage\u0020via\u0020AJAX.",
            "url": "classes/BULK-IMPORT-Inc-Admin-Menu.html#method_save_profit_percentage_callback"
        },                {
            "fqsen": "\\BULK_IMPORT\\Inc\\Admin_Menu\u003A\u003Aget_product_price_from_db\u0028\u0029",
            "name": "get_product_price_from_db",
            "summary": "Fetch\u0020the\u0020product\u0020price\u0020from\u0020the\u0020database.",
            "url": "classes/BULK-IMPORT-Inc-Admin-Menu.html#method_get_product_price_from_db"
        },                {
            "fqsen": "\\BULK_IMPORT\\Inc\\Api_Endpoints",
            "name": "Api_Endpoints",
            "summary": "Class\u0020Api_Endpoints",
            "url": "classes/BULK-IMPORT-Inc-Api-Endpoints.html"
        },                {
            "fqsen": "\\BULK_IMPORT\\Inc\\Api_Endpoints\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "Constructor.",
            "url": "classes/BULK-IMPORT-Inc-Api-Endpoints.html#method___construct"
        },                {
            "fqsen": "\\BULK_IMPORT\\Inc\\Api_Endpoints\u003A\u003Asetup_hooks\u0028\u0029",
            "name": "setup_hooks",
            "summary": "Setup\u0020hooks.",
            "url": "classes/BULK-IMPORT-Inc-Api-Endpoints.html#method_setup_hooks"
        },                {
            "fqsen": "\\BULK_IMPORT\\Inc\\Api_Endpoints\u003A\u003Aregister_api_endpoints\u0028\u0029",
            "name": "register_api_endpoints",
            "summary": "Register\u0020API\u0020Endpoints.",
            "url": "classes/BULK-IMPORT-Inc-Api-Endpoints.html#method_register_api_endpoints"
        },                {
            "fqsen": "\\BULK_IMPORT\\Inc\\Api_Endpoints\u003A\u003Abulk_product_import_callback\u0028\u0029",
            "name": "bulk_product_import_callback",
            "summary": "Callback\u0020for\u0020the\u0020\u0060\/server\u002Dstatus\u0060\u0020endpoint.",
            "url": "classes/BULK-IMPORT-Inc-Api-Endpoints.html#method_bulk_product_import_callback"
        },                {
            "fqsen": "\\BULK_IMPORT\\Inc\\Api_Endpoints\u003A\u003Aserver_status_check\u0028\u0029",
            "name": "server_status_check",
            "summary": "Server\u0020status\u0020check.",
            "url": "classes/BULK-IMPORT-Inc-Api-Endpoints.html#method_server_status_check"
        },                {
            "fqsen": "\\BULK_IMPORT\\Inc\\Api_Endpoints\u003A\u003Abulk_product_delete_callback\u0028\u0029",
            "name": "bulk_product_delete_callback",
            "summary": "Callback\u0020for\u0020the\u0020\u0060\/delete\u002Dproducts\u0060\u0020endpoint.",
            "url": "classes/BULK-IMPORT-Inc-Api-Endpoints.html#method_bulk_product_delete_callback"
        },                {
            "fqsen": "\\BULK_IMPORT\\Inc\\Api_Endpoints\u003A\u003Abulk_products_delete\u0028\u0029",
            "name": "bulk_products_delete",
            "summary": "Deletes\u0020all\u0020WooCommerce\u0020products\u0020permanently.",
            "url": "classes/BULK-IMPORT-Inc-Api-Endpoints.html#method_bulk_products_delete"
        },                {
            "fqsen": "\\BULK_IMPORT\\Inc\\Api_Endpoints\u003A\u003Abulk_product_trash_delete_callback\u0028\u0029",
            "name": "bulk_product_trash_delete_callback",
            "summary": "Callback\u0020for\u0020the\u0020\u0060\/delete\u002Dtrash\u002Dproducts\u0060\u0020endpoint.",
            "url": "classes/BULK-IMPORT-Inc-Api-Endpoints.html#method_bulk_product_trash_delete_callback"
        },                {
            "fqsen": "\\BULK_IMPORT\\Inc\\Api_Endpoints\u003A\u003Abulk_products_trash_delete\u0028\u0029",
            "name": "bulk_products_trash_delete",
            "summary": "Deletes\u0020all\u0020trashed\u0020WooCommerce\u0020products\u0020permanently.",
            "url": "classes/BULK-IMPORT-Inc-Api-Endpoints.html#method_bulk_products_trash_delete"
        },                {
            "fqsen": "\\BULK_IMPORT\\Inc\\Api_Endpoints\u003A\u003Adelete_woo_cats_callback\u0028\u0029",
            "name": "delete_woo_cats_callback",
            "summary": "Callback\u0020for\u0020the\u0020\u0060\/delete\u002Dwoo\u002Dcats\u0060\u0020endpoint.",
            "url": "classes/BULK-IMPORT-Inc-Api-Endpoints.html#method_delete_woo_cats_callback"
        },                {
            "fqsen": "\\BULK_IMPORT\\Inc\\Api_Endpoints\u003A\u003Adelete_woo_cats\u0028\u0029",
            "name": "delete_woo_cats",
            "summary": "Deletes\u0020all\u0020WooCommerce\u0020product\u0020categories.",
            "url": "classes/BULK-IMPORT-Inc-Api-Endpoints.html#method_delete_woo_cats"
        },                {
            "fqsen": "\\BULK_IMPORT\\Inc\\Api_Endpoints\u003A\u003Atest_wp_jobs\u0028\u0029",
            "name": "test_wp_jobs",
            "summary": "Callback\u0020for\u0020the\u0020\u0060\/test\u002Djob\u0060\u0020endpoint.",
            "url": "classes/BULK-IMPORT-Inc-Api-Endpoints.html#method_test_wp_jobs"
        },                {
            "fqsen": "\\BULK_IMPORT\\Inc\\Api_Endpoints\u003A\u003Aput_program_logs\u0028\u0029",
            "name": "put_program_logs",
            "summary": "Logs\u0020data\u0020into\u0020a\u0020file.",
            "url": "classes/BULK-IMPORT-Inc-Api-Endpoints.html#method_put_program_logs"
        },                {
            "fqsen": "\\BULK_IMPORT\\Inc\\Autoloader",
            "name": "Autoloader",
            "summary": "Class\u0020Autoloader",
            "url": "classes/BULK-IMPORT-Inc-Autoloader.html"
        },                {
            "fqsen": "\\BULK_IMPORT\\Inc\\Autoloader\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "Constructor.",
            "url": "classes/BULK-IMPORT-Inc-Autoloader.html#method___construct"
        },                {
            "fqsen": "\\BULK_IMPORT\\Inc\\Create_Order",
            "name": "Create_Order",
            "summary": "",
            "url": "classes/BULK-IMPORT-Inc-Create-Order.html"
        },                {
            "fqsen": "\\BULK_IMPORT\\Inc\\Create_Order\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/BULK-IMPORT-Inc-Create-Order.html#method___construct"
        },                {
            "fqsen": "\\BULK_IMPORT\\Inc\\Create_Order\u003A\u003Asetup_hooks\u0028\u0029",
            "name": "setup_hooks",
            "summary": "",
            "url": "classes/BULK-IMPORT-Inc-Create-Order.html#method_setup_hooks"
        },                {
            "fqsen": "\\BULK_IMPORT\\Inc\\Create_Order\u003A\u003Aupdate_cart_item_price\u0028\u0029",
            "name": "update_cart_item_price",
            "summary": "Update\u0020the\u0020price\u0020of\u0020items\u0020in\u0020the\u0020WooCommerce\u0020cart\u0020dynamically.",
            "url": "classes/BULK-IMPORT-Inc-Create-Order.html#method_update_cart_item_price"
        },                {
            "fqsen": "\\BULK_IMPORT\\Inc\\Create_Order\u003A\u003Acreate_order\u0028\u0029",
            "name": "create_order",
            "summary": "Creates\u0020and\u0020processes\u0020an\u0020order\u0020by\u0020interacting\u0020with\u0020an\u0020external\u0020API.",
            "url": "classes/BULK-IMPORT-Inc-Create-Order.html#method_create_order"
        },                {
            "fqsen": "\\BULK_IMPORT\\Inc\\Create_Order\u003A\u003Adisplay_printing_positions_on_thank_you_page\u0028\u0029",
            "name": "display_printing_positions_on_thank_you_page",
            "summary": "Displays\u0020printing\u0020positions\u0020and\u0020related\u0020details\u0020on\u0020the\u0020WooCommerce\u0020\u0022Thank\u0020You\u0022\u0020page.",
            "url": "classes/BULK-IMPORT-Inc-Create-Order.html#method_display_printing_positions_on_thank_you_page"
        },                {
            "fqsen": "\\BULK_IMPORT\\Inc\\Create_Order\u003A\u003Adisplay_printing_positions_on_order_page\u0028\u0029",
            "name": "display_printing_positions_on_order_page",
            "summary": "Displays\u0020printing\u0020positions\u0020and\u0020related\u0020details\u0020on\u0020the\u0020WooCommerce\u0020order\u0020page\u0020in\u0020the\u0020admin\u0020panel.",
            "url": "classes/BULK-IMPORT-Inc-Create-Order.html#method_display_printing_positions_on_order_page"
        },                {
            "fqsen": "\\BULK_IMPORT\\Inc\\Create_Order\u003A\u003Acall_api\u0028\u0029",
            "name": "call_api",
            "summary": "Handles\u0020API\u0020call\u0020to\u0020submit\u0020order\u0020details.",
            "url": "classes/BULK-IMPORT-Inc-Create-Order.html#method_call_api"
        },                {
            "fqsen": "\\BULK_IMPORT\\Inc\\Create_Order\u003A\u003Aput_program_logs\u0028\u0029",
            "name": "put_program_logs",
            "summary": "",
            "url": "classes/BULK-IMPORT-Inc-Create-Order.html#method_put_program_logs"
        },                {
            "fqsen": "\\BULK_IMPORT\\Inc\\Customize_Product_Page",
            "name": "Customize_Product_Page",
            "summary": "",
            "url": "classes/BULK-IMPORT-Inc-Customize-Product-Page.html"
        },                {
            "fqsen": "\\BULK_IMPORT\\Inc\\Customize_Product_Page\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/BULK-IMPORT-Inc-Customize-Product-Page.html#method___construct"
        },                {
            "fqsen": "\\BULK_IMPORT\\Inc\\Customize_Product_Page\u003A\u003Asetup_hooks\u0028\u0029",
            "name": "setup_hooks",
            "summary": "",
            "url": "classes/BULK-IMPORT-Inc-Customize-Product-Page.html#method_setup_hooks"
        },                {
            "fqsen": "\\BULK_IMPORT\\Inc\\Customize_Product_Page\u003A\u003Adisplay_product_info_callback\u0028\u0029",
            "name": "display_product_info_callback",
            "summary": "Callback\u0020function\u0020to\u0020display\u0020product\u0020details\u0020on\u0020the\u0020front\u002Dend.",
            "url": "classes/BULK-IMPORT-Inc-Customize-Product-Page.html#method_display_product_info_callback"
        },                {
            "fqsen": "\\BULK_IMPORT\\Inc\\Customize_Product_Page\u003A\u003Adisplay_product_sku_callback\u0028\u0029",
            "name": "display_product_sku_callback",
            "summary": "Display\u0020the\u0020product\u0020SKU\u0020in\u0020a\u0020custom\u0020HTML\u0020structure.",
            "url": "classes/BULK-IMPORT-Inc-Customize-Product-Page.html#method_display_product_sku_callback"
        },                {
            "fqsen": "\\BULK_IMPORT\\Inc\\Customize_Product_Page\u003A\u003Acustom_product_configurator_callback\u0028\u0029",
            "name": "custom_product_configurator_callback",
            "summary": "Custom\u0020product\u0020configurator\u0020callback.\u0020Configure\u0020the\u0020product\u0020based\u0020on\u0020the\u0020selected\u0020printing\u0020technique.",
            "url": "classes/BULK-IMPORT-Inc-Customize-Product-Page.html#method_custom_product_configurator_callback"
        },                {
            "fqsen": "\\BULK_IMPORT\\Inc\\Customize_Product_Page\u003A\u003Acustom_product_configurator_mto_link_callback\u0028\u0029",
            "name": "custom_product_configurator_mto_link_callback",
            "summary": "Generates\u0020and\u0020returns\u0020the\u0020HTML\u0020for\u0020the\u0020custom\u0020product\u0020configurator\u0020MTO\u0020\u0028Made\u0020to\u0020Order\u0029\u0020link.",
            "url": "classes/BULK-IMPORT-Inc-Customize-Product-Page.html#method_custom_product_configurator_mto_link_callback"
        },                {
            "fqsen": "\\BULK_IMPORT\\Inc\\Customize_Product_Page\u003A\u003Afetch_product_data_from_db\u0028\u0029",
            "name": "fetch_product_data_from_db",
            "summary": "Fetches\u0020product\u0020data\u0020from\u0020the\u0020database\u0020based\u0020on\u0020the\u0020product\u0020number.",
            "url": "classes/BULK-IMPORT-Inc-Customize-Product-Page.html#method_fetch_product_data_from_db"
        },                {
            "fqsen": "\\BULK_IMPORT\\Inc\\Customize_Product_Page\u003A\u003Afetch_product_print_data_from_db\u0028\u0029",
            "name": "fetch_product_print_data_from_db",
            "summary": "Fetches\u0020print\u0020data\u0020for\u0020a\u0020product\u0020from\u0020the\u0020database\u0020based\u0020on\u0020the\u0020master\u0020code.",
            "url": "classes/BULK-IMPORT-Inc-Customize-Product-Page.html#method_fetch_product_print_data_from_db"
        },                {
            "fqsen": "\\BULK_IMPORT\\Inc\\Customize_Product_Page\u003A\u003Acustom_add_to_cart_handler\u0028\u0029",
            "name": "custom_add_to_cart_handler",
            "summary": "Handles\u0020adding\u0020a\u0020product\u0020to\u0020the\u0020WooCommerce\u0020cart.",
            "url": "classes/BULK-IMPORT-Inc-Customize-Product-Page.html#method_custom_add_to_cart_handler"
        },                {
            "fqsen": "\\BULK_IMPORT\\Inc\\Customize_Product_Page\u003A\u003Ahandle_file_upload\u0028\u0029",
            "name": "handle_file_upload",
            "summary": "Handles\u0020file\u0020upload\u0020for\u0020artwork,\u0020mockup,\u0020and\u0020instructions.",
            "url": "classes/BULK-IMPORT-Inc-Customize-Product-Page.html#method_handle_file_upload"
        },                {
            "fqsen": "\\BULK_IMPORT\\Inc\\Customize_Product_Page\u003A\u003Aget_technique_label\u0028\u0029",
            "name": "get_technique_label",
            "summary": "Fetches\u0020the\u0020technique\u0020label\u0020based\u0020on\u0020the\u0020technique\u0020ID\u0020provided\u0020in\u0020the\u0020POST\u0020request.",
            "url": "classes/BULK-IMPORT-Inc-Customize-Product-Page.html#method_get_technique_label"
        },                {
            "fqsen": "\\BULK_IMPORT\\Inc\\Customize_Product_Page\u003A\u003Aget_technique_label_from_db\u0028\u0029",
            "name": "get_technique_label_from_db",
            "summary": "Retrieves\u0020the\u0020technique\u0020label\u0020from\u0020the\u0020database\u0020based\u0020on\u0020the\u0020given\u0020technique\u0020ID.",
            "url": "classes/BULK-IMPORT-Inc-Customize-Product-Page.html#method_get_technique_label_from_db"
        },                {
            "fqsen": "\\BULK_IMPORT\\Inc\\Customize_Product_Page\u003A\u003Aget_print_price_data_from_db\u0028\u0029",
            "name": "get_print_price_data_from_db",
            "summary": "Retrieves\u0020print\u0020price\u0020data\u0020for\u0020a\u0020given\u0020technique\u0020ID\u0020from\u0020the\u0020database.",
            "url": "classes/BULK-IMPORT-Inc-Customize-Product-Page.html#method_get_print_price_data_from_db"
        },                {
            "fqsen": "\\BULK_IMPORT\\Inc\\Customize_Product_Page\u003A\u003Aget_textile_product_stock_from_db\u0028\u0029",
            "name": "get_textile_product_stock_from_db",
            "summary": "Fetches\u0020the\u0020stock\u0020for\u0020a\u0020specific\u0020product\u0020SKU\u0020from\u0020the\u0020database.",
            "url": "classes/BULK-IMPORT-Inc-Customize-Product-Page.html#method_get_textile_product_stock_from_db"
        },                {
            "fqsen": "\\BULK_IMPORT\\Inc\\Customize_Product_Page\u003A\u003Aget_variants_from_db\u0028\u0029",
            "name": "get_variants_from_db",
            "summary": "",
            "url": "classes/BULK-IMPORT-Inc-Customize-Product-Page.html#method_get_variants_from_db"
        },                {
            "fqsen": "\\BULK_IMPORT\\Inc\\Customize_Product_Page\u003A\u003Aget_color_hex_from_db_based_on_color_code\u0028\u0029",
            "name": "get_color_hex_from_db_based_on_color_code",
            "summary": "",
            "url": "classes/BULK-IMPORT-Inc-Customize-Product-Page.html#method_get_color_hex_from_db_based_on_color_code"
        },                {
            "fqsen": "\\BULK_IMPORT\\Inc\\Customize_Product_Page\u003A\u003Aget_all_color_hex_from_db\u0028\u0029",
            "name": "get_all_color_hex_from_db",
            "summary": "",
            "url": "classes/BULK-IMPORT-Inc-Customize-Product-Page.html#method_get_all_color_hex_from_db"
        },                {
            "fqsen": "\\BULK_IMPORT\\Inc\\Customize_Product_Page\u003A\u003Aput_program_logs\u0028\u0029",
            "name": "put_program_logs",
            "summary": "",
            "url": "classes/BULK-IMPORT-Inc-Customize-Product-Page.html#method_put_program_logs"
        },                {
            "fqsen": "\\BULK_IMPORT\\Inc\\Customize_Product_Page\u003A\u003A\u0024product_id",
            "name": "product_id",
            "summary": "",
            "url": "classes/BULK-IMPORT-Inc-Customize-Product-Page.html#property_product_id"
        },                {
            "fqsen": "\\BULK_IMPORT\\Inc\\Customize_Product_Page\u003A\u003A\u0024product_number",
            "name": "product_number",
            "summary": "",
            "url": "classes/BULK-IMPORT-Inc-Customize-Product-Page.html#property_product_number"
        },                {
            "fqsen": "\\BULK_IMPORT\\Inc\\Customize_Product_Page\u003A\u003A\u0024product_name",
            "name": "product_name",
            "summary": "",
            "url": "classes/BULK-IMPORT-Inc-Customize-Product-Page.html#property_product_name"
        },                {
            "fqsen": "\\BULK_IMPORT\\Inc\\Customize_Product_Page\u003A\u003A\u0024attachment_id",
            "name": "attachment_id",
            "summary": "",
            "url": "classes/BULK-IMPORT-Inc-Customize-Product-Page.html#property_attachment_id"
        },                {
            "fqsen": "\\BULK_IMPORT\\Inc\\Customize_Product_Page\u003A\u003A\u0024product_small_image",
            "name": "product_small_image",
            "summary": "",
            "url": "classes/BULK-IMPORT-Inc-Customize-Product-Page.html#property_product_small_image"
        },                {
            "fqsen": "\\BULK_IMPORT\\Inc\\Customize_Product_Page\u003A\u003A\u0024category_id",
            "name": "category_id",
            "summary": "",
            "url": "classes/BULK-IMPORT-Inc-Customize-Product-Page.html#property_category_id"
        },                {
            "fqsen": "\\BULK_IMPORT\\Inc\\Customize_Product_Page\u003A\u003A\u0024category_url",
            "name": "category_url",
            "summary": "",
            "url": "classes/BULK-IMPORT-Inc-Customize-Product-Page.html#property_category_url"
        },                {
            "fqsen": "\\BULK_IMPORT\\Inc\\Customize_Product_Page\u003A\u003A\u0024master_code",
            "name": "master_code",
            "summary": "",
            "url": "classes/BULK-IMPORT-Inc-Customize-Product-Page.html#property_master_code"
        },                {
            "fqsen": "\\BULK_IMPORT\\Inc\\Customize_Product_Page\u003A\u003A\u0024product_stock",
            "name": "product_stock",
            "summary": "",
            "url": "classes/BULK-IMPORT-Inc-Customize-Product-Page.html#property_product_stock"
        },                {
            "fqsen": "\\BULK_IMPORT\\Inc\\Customize_Product_Page\u003A\u003A\u0024number_of_print_positions",
            "name": "number_of_print_positions",
            "summary": "",
            "url": "classes/BULK-IMPORT-Inc-Customize-Product-Page.html#property_number_of_print_positions"
        },                {
            "fqsen": "\\BULK_IMPORT\\Inc\\Customize_Product_Page\u003A\u003A\u0024color_group",
            "name": "color_group",
            "summary": "",
            "url": "classes/BULK-IMPORT-Inc-Customize-Product-Page.html#property_color_group"
        },                {
            "fqsen": "\\BULK_IMPORT\\Inc\\Customize_Product_Page\u003A\u003A\u0024color_hex",
            "name": "color_hex",
            "summary": "",
            "url": "classes/BULK-IMPORT-Inc-Customize-Product-Page.html#property_color_hex"
        },                {
            "fqsen": "\\BULK_IMPORT\\Inc\\Customize_Product_Page\u003A\u003A\u0024color_description",
            "name": "color_description",
            "summary": "",
            "url": "classes/BULK-IMPORT-Inc-Customize-Product-Page.html#property_color_description"
        },                {
            "fqsen": "\\BULK_IMPORT\\Inc\\Customize_Product_Page\u003A\u003A\u0024product_price",
            "name": "product_price",
            "summary": "",
            "url": "classes/BULK-IMPORT-Inc-Customize-Product-Page.html#property_product_price"
        },                {
            "fqsen": "\\BULK_IMPORT\\Inc\\Customize_Product_Page\u003A\u003A\u0024currency_symbol",
            "name": "currency_symbol",
            "summary": "",
            "url": "classes/BULK-IMPORT-Inc-Customize-Product-Page.html#property_currency_symbol"
        },                {
            "fqsen": "\\BULK_IMPORT\\Inc\\Customize_Product_Page\u003A\u003A\u0024technique_labels",
            "name": "technique_labels",
            "summary": "",
            "url": "classes/BULK-IMPORT-Inc-Customize-Product-Page.html#property_technique_labels"
        },                {
            "fqsen": "\\BULK_IMPORT\\Inc\\Customize_Product_Page\u003A\u003A\u0024type_of_product",
            "name": "type_of_product",
            "summary": "",
            "url": "classes/BULK-IMPORT-Inc-Customize-Product-Page.html#property_type_of_product"
        },                {
            "fqsen": "\\BULK_IMPORT\\Inc\\Display_Additional_Info",
            "name": "Display_Additional_Info",
            "summary": "",
            "url": "classes/BULK-IMPORT-Inc-Display-Additional-Info.html"
        },                {
            "fqsen": "\\BULK_IMPORT\\Inc\\Display_Additional_Info\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/BULK-IMPORT-Inc-Display-Additional-Info.html#method___construct"
        },                {
            "fqsen": "\\BULK_IMPORT\\Inc\\Display_Additional_Info\u003A\u003Asetup_hooks\u0028\u0029",
            "name": "setup_hooks",
            "summary": "",
            "url": "classes/BULK-IMPORT-Inc-Display-Additional-Info.html#method_setup_hooks"
        },                {
            "fqsen": "\\BULK_IMPORT\\Inc\\Display_Additional_Info\u003A\u003Adisplay_additional_info\u0028\u0029",
            "name": "display_additional_info",
            "summary": "",
            "url": "classes/BULK-IMPORT-Inc-Display-Additional-Info.html#method_display_additional_info"
        },                {
            "fqsen": "\\BULK_IMPORT\\Inc\\Enqueue_Assets",
            "name": "Enqueue_Assets",
            "summary": "",
            "url": "classes/BULK-IMPORT-Inc-Enqueue-Assets.html"
        },                {
            "fqsen": "\\BULK_IMPORT\\Inc\\Enqueue_Assets\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/BULK-IMPORT-Inc-Enqueue-Assets.html#method___construct"
        },                {
            "fqsen": "\\BULK_IMPORT\\Inc\\Enqueue_Assets\u003A\u003Asetup_hooks\u0028\u0029",
            "name": "setup_hooks",
            "summary": "",
            "url": "classes/BULK-IMPORT-Inc-Enqueue-Assets.html#method_setup_hooks"
        },                {
            "fqsen": "\\BULK_IMPORT\\Inc\\Enqueue_Assets\u003A\u003Aenqueue_css\u0028\u0029",
            "name": "enqueue_css",
            "summary": "",
            "url": "classes/BULK-IMPORT-Inc-Enqueue-Assets.html#method_enqueue_css"
        },                {
            "fqsen": "\\BULK_IMPORT\\Inc\\Enqueue_Assets\u003A\u003Aenqueue_js\u0028\u0029",
            "name": "enqueue_js",
            "summary": "",
            "url": "classes/BULK-IMPORT-Inc-Enqueue-Assets.html#method_enqueue_js"
        },                {
            "fqsen": "\\BULK_IMPORT\\Inc\\Enqueue_Assets\u003A\u003Aadmin_enqueue_style\u0028\u0029",
            "name": "admin_enqueue_style",
            "summary": "",
            "url": "classes/BULK-IMPORT-Inc-Enqueue-Assets.html#method_admin_enqueue_style"
        },                {
            "fqsen": "\\BULK_IMPORT\\Inc\\Enqueue_Assets\u003A\u003Aadmin_enqueue_script\u0028\u0029",
            "name": "admin_enqueue_script",
            "summary": "",
            "url": "classes/BULK-IMPORT-Inc-Enqueue-Assets.html#method_admin_enqueue_script"
        },                {
            "fqsen": "\\BULK_IMPORT\\Inc\\Enqueue_Assets\u003A\u003Aget_all_color_hex_from_db\u0028\u0029",
            "name": "get_all_color_hex_from_db",
            "summary": "",
            "url": "classes/BULK-IMPORT-Inc-Enqueue-Assets.html#method_get_all_color_hex_from_db"
        },                {
            "fqsen": "\\BULK_IMPORT\\Inc\\Enqueue_Assets\u003A\u003A\u0024all_color_hex",
            "name": "all_color_hex",
            "summary": "",
            "url": "classes/BULK-IMPORT-Inc-Enqueue-Assets.html#property_all_color_hex"
        },                {
            "fqsen": "\\BULK_IMPORT\\Inc\\Class_Template",
            "name": "Class_Template",
            "summary": "",
            "url": "classes/BULK-IMPORT-Inc-Class-Template.html"
        },                {
            "fqsen": "\\BULK_IMPORT\\Inc\\Class_Template\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/BULK-IMPORT-Inc-Class-Template.html#method___construct"
        },                {
            "fqsen": "\\BULK_IMPORT\\Inc\\Class_Template\u003A\u003Asetup_hooks\u0028\u0029",
            "name": "setup_hooks",
            "summary": "",
            "url": "classes/BULK-IMPORT-Inc-Class-Template.html#method_setup_hooks"
        },                {
            "fqsen": "\\bulk_products_import\u0028\u0029",
            "name": "bulk_products_import",
            "summary": "",
            "url": "namespaces/default.html#function_bulk_products_import"
        },                {
            "fqsen": "\\sync_products_api_callback\u0028\u0029",
            "name": "sync_products_api_callback",
            "summary": "",
            "url": "namespaces/default.html#function_sync_products_api_callback"
        },                {
            "fqsen": "\\insert_products_db_api_callback\u0028\u0029",
            "name": "insert_products_db_api_callback",
            "summary": "",
            "url": "namespaces/default.html#function_insert_products_db_api_callback"
        },                {
            "fqsen": "\\insert_price_db_api_callback\u0028\u0029",
            "name": "insert_price_db_api_callback",
            "summary": "",
            "url": "namespaces/default.html#function_insert_price_db_api_callback"
        },                {
            "fqsen": "\\insert_stock_db_api_callback\u0028\u0029",
            "name": "insert_stock_db_api_callback",
            "summary": "",
            "url": "namespaces/default.html#function_insert_stock_db_api_callback"
        },                {
            "fqsen": "\\insert_print_data_db_api_callback\u0028\u0029",
            "name": "insert_print_data_db_api_callback",
            "summary": "",
            "url": "namespaces/default.html#function_insert_print_data_db_api_callback"
        },                {
            "fqsen": "\\insert_print_price_data_db_api_callback\u0028\u0029",
            "name": "insert_print_price_data_db_api_callback",
            "summary": "",
            "url": "namespaces/default.html#function_insert_print_price_data_db_api_callback"
        },                {
            "fqsen": "\\insert_print_price_data_label_db_api_callback\u0028\u0029",
            "name": "insert_print_price_data_label_db_api_callback",
            "summary": "",
            "url": "namespaces/default.html#function_insert_print_price_data_label_db_api_callback"
        },                {
            "fqsen": "\\transform_color_list_callback\u0028\u0029",
            "name": "transform_color_list_callback",
            "summary": "",
            "url": "namespaces/default.html#function_transform_color_list_callback"
        },                {
            "fqsen": "\\insert_color_group_db_callback\u0028\u0029",
            "name": "insert_color_group_db_callback",
            "summary": "",
            "url": "namespaces/default.html#function_insert_color_group_db_callback"
        },                {
            "fqsen": "\\insert_color_hex_db_callback\u0028\u0029",
            "name": "insert_color_hex_db_callback",
            "summary": "",
            "url": "namespaces/default.html#function_insert_color_hex_db_callback"
        },                {
            "fqsen": "\\sync_products\u0028\u0029",
            "name": "sync_products",
            "summary": "",
            "url": "namespaces/default.html#function_sync_products"
        },                {
            "fqsen": "\\remove_sync_products\u0028\u0029",
            "name": "remove_sync_products",
            "summary": "",
            "url": "namespaces/default.html#function_remove_sync_products"
        },                {
            "fqsen": "\\sync_stock\u0028\u0029",
            "name": "sync_stock",
            "summary": "",
            "url": "namespaces/default.html#function_sync_stock"
        },                {
            "fqsen": "\\remove_sync_stock\u0028\u0029",
            "name": "remove_sync_stock",
            "summary": "",
            "url": "namespaces/default.html#function_remove_sync_stock"
        },                {
            "fqsen": "\\sync_price\u0028\u0029",
            "name": "sync_price",
            "summary": "",
            "url": "namespaces/default.html#function_sync_price"
        },                {
            "fqsen": "\\sync_print_price\u0028\u0029",
            "name": "sync_print_price",
            "summary": "",
            "url": "namespaces/default.html#function_sync_print_price"
        },                {
            "fqsen": "\\remove_sync_price\u0028\u0029",
            "name": "remove_sync_price",
            "summary": "",
            "url": "namespaces/default.html#function_remove_sync_price"
        },                {
            "fqsen": "\\remove_sync_print_price\u0028\u0029",
            "name": "remove_sync_print_price",
            "summary": "",
            "url": "namespaces/default.html#function_remove_sync_print_price"
        },                {
            "fqsen": "\\sync_products_print_data\u0028\u0029",
            "name": "sync_products_print_data",
            "summary": "",
            "url": "namespaces/default.html#function_sync_products_print_data"
        },                {
            "fqsen": "\\remove_products_print_data\u0028\u0029",
            "name": "remove_products_print_data",
            "summary": "",
            "url": "namespaces/default.html#function_remove_products_print_data"
        },                {
            "fqsen": "\\sync_products_print_data_labels\u0028\u0029",
            "name": "sync_products_print_data_labels",
            "summary": "",
            "url": "namespaces/default.html#function_sync_products_print_data_labels"
        },                {
            "fqsen": "\\remove_products_print_data_labels\u0028\u0029",
            "name": "remove_products_print_data_labels",
            "summary": "",
            "url": "namespaces/default.html#function_remove_products_print_data_labels"
        },                {
            "fqsen": "\\sync_color_group\u0028\u0029",
            "name": "sync_color_group",
            "summary": "",
            "url": "namespaces/default.html#function_sync_color_group"
        },                {
            "fqsen": "\\remove_color_group\u0028\u0029",
            "name": "remove_color_group",
            "summary": "",
            "url": "namespaces/default.html#function_remove_color_group"
        },                {
            "fqsen": "\\sync_color_hex_list\u0028\u0029",
            "name": "sync_color_hex_list",
            "summary": "",
            "url": "namespaces/default.html#function_sync_color_hex_list"
        },                {
            "fqsen": "\\remove_color_hex_list\u0028\u0029",
            "name": "remove_color_hex_list",
            "summary": "",
            "url": "namespaces/default.html#function_remove_color_hex_list"
        },                {
            "fqsen": "\\create_db_tables\u0028\u0029",
            "name": "create_db_tables",
            "summary": "",
            "url": "namespaces/default.html#function_create_db_tables"
        },                {
            "fqsen": "\\remove_db_tables\u0028\u0029",
            "name": "remove_db_tables",
            "summary": "",
            "url": "namespaces/default.html#function_remove_db_tables"
        },                {
            "fqsen": "\\products_import_woocommerce\u0028\u0029",
            "name": "products_import_woocommerce",
            "summary": "Function\u0020to\u0020insert\u0020products\u0020into\u0020WooCommerce\nFetch\u0020product\u0020data\u0020from\u0020database\nProcess\u0020product\u0020data\u0020and\u0020insert\u0020into\u0020WooCommerce",
            "url": "namespaces/default.html#function_products_import_woocommerce"
        },                {
            "fqsen": "\\update_product_additional_information\u0028\u0029",
            "name": "update_product_additional_information",
            "summary": "Update\u0020Product\u0020Additional\u0020Information",
            "url": "namespaces/default.html#function_update_product_additional_information"
        },                {
            "fqsen": "\\set_product_images\u0028\u0029",
            "name": "set_product_images",
            "summary": "Set\u0020Product\u0020Images",
            "url": "namespaces/default.html#function_set_product_images"
        },                {
            "fqsen": "\\set_product_images_with_unique_image_name\u0028\u0029",
            "name": "set_product_images_with_unique_image_name",
            "summary": "Set\u0020product\u0020images\u0020with\u0020unique\u0020image\u0020name",
            "url": "namespaces/default.html#function_set_product_images_with_unique_image_name"
        },                {
            "fqsen": "\\truncate_table\u0028\u0029",
            "name": "truncate_table",
            "summary": "",
            "url": "namespaces/default.html#function_truncate_table"
        },                {
            "fqsen": "\\fetch_products_from_api\u0028\u0029",
            "name": "fetch_products_from_api",
            "summary": "",
            "url": "namespaces/default.html#function_fetch_products_from_api"
        },                {
            "fqsen": "\\insert_products_db\u0028\u0029",
            "name": "insert_products_db",
            "summary": "",
            "url": "namespaces/default.html#function_insert_products_db"
        },                {
            "fqsen": "\\fetch_price_from_api\u0028\u0029",
            "name": "fetch_price_from_api",
            "summary": "",
            "url": "namespaces/default.html#function_fetch_price_from_api"
        },                {
            "fqsen": "\\insert_price_db\u0028\u0029",
            "name": "insert_price_db",
            "summary": "",
            "url": "namespaces/default.html#function_insert_price_db"
        },                {
            "fqsen": "\\fetch_stock_from_api\u0028\u0029",
            "name": "fetch_stock_from_api",
            "summary": "",
            "url": "namespaces/default.html#function_fetch_stock_from_api"
        },                {
            "fqsen": "\\insert_stock_db\u0028\u0029",
            "name": "insert_stock_db",
            "summary": "",
            "url": "namespaces/default.html#function_insert_stock_db"
        },                {
            "fqsen": "\\fetch_product_print_data\u0028\u0029",
            "name": "fetch_product_print_data",
            "summary": "",
            "url": "namespaces/default.html#function_fetch_product_print_data"
        },                {
            "fqsen": "\\insert_product_print_data_db\u0028\u0029",
            "name": "insert_product_print_data_db",
            "summary": "",
            "url": "namespaces/default.html#function_insert_product_print_data_db"
        },                {
            "fqsen": "\\insert_product_print_data_labels_db\u0028\u0029",
            "name": "insert_product_print_data_labels_db",
            "summary": "",
            "url": "namespaces/default.html#function_insert_product_print_data_labels_db"
        },                {
            "fqsen": "\\fetch_product_print_price_data\u0028\u0029",
            "name": "fetch_product_print_price_data",
            "summary": "",
            "url": "namespaces/default.html#function_fetch_product_print_price_data"
        },                {
            "fqsen": "\\insert_product_print_price_data_db\u0028\u0029",
            "name": "insert_product_print_price_data_db",
            "summary": "",
            "url": "namespaces/default.html#function_insert_product_print_price_data_db"
        },                {
            "fqsen": "\\insert_color_group_db\u0028\u0029",
            "name": "insert_color_group_db",
            "summary": "",
            "url": "namespaces/default.html#function_insert_color_group_db"
        },                {
            "fqsen": "\\insert_color_hex_db\u0028\u0029",
            "name": "insert_color_hex_db",
            "summary": "",
            "url": "namespaces/default.html#function_insert_color_hex_db"
        },                {
            "fqsen": "\\transform_color_list\u0028\u0029",
            "name": "transform_color_list",
            "summary": "",
            "url": "namespaces/default.html#function_transform_color_list"
        },                {
            "fqsen": "\\BULK_IMPORT\\Inc\\Helpers\\autoloader\u0028\u0029",
            "name": "autoloader",
            "summary": "Auto\u0020loader\u0020function.",
            "url": "namespaces/bulk-import-inc-helpers.html#function_autoloader"
        },                {
            "fqsen": "\\dd\u0028\u0029",
            "name": "dd",
            "summary": "Dump\u0020and\u0020die.",
            "url": "namespaces/default.html#function_dd"
        },                {
            "fqsen": "\\pd\u0028\u0029",
            "name": "pd",
            "summary": "Print\u0020and\u0020die.",
            "url": "namespaces/default.html#function_pd"
        },                {
            "fqsen": "\\put_program_logs\u0028\u0029",
            "name": "put_program_logs",
            "summary": "Function\u0020to\u0020save\u0020response\u0020data\u0020to\u0020a\u0020file.",
            "url": "namespaces/default.html#function_put_program_logs"
        },                {
            "fqsen": "\\Sheet_Import",
            "name": "Sheet_Import",
            "summary": "",
            "url": "classes/Sheet-Import.html"
        },                {
            "fqsen": "\\Sheet_Import\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Sheet-Import.html#method___construct"
        },                {
            "fqsen": "\\Sheet_Import\u003A\u003AfetchProductsFromSheets\u0028\u0029",
            "name": "fetchProductsFromSheets",
            "summary": "",
            "url": "classes/Sheet-Import.html#method_fetchProductsFromSheets"
        },                {
            "fqsen": "\\Sheet_Import\u003A\u003AinsertProductsToDatabase\u0028\u0029",
            "name": "insertProductsToDatabase",
            "summary": "",
            "url": "classes/Sheet-Import.html#method_insertProductsToDatabase"
        },                {
            "fqsen": "\\Sheet_Import\u003A\u003A\u0024client",
            "name": "client",
            "summary": "",
            "url": "classes/Sheet-Import.html#property_client"
        },                {
            "fqsen": "\\Sheet_Import\u003A\u003A\u0024service",
            "name": "service",
            "summary": "",
            "url": "classes/Sheet-Import.html#property_service"
        },                {
            "fqsen": "\\Sheet_Import\u003A\u003A\u0024spreadsheetID",
            "name": "spreadsheetID",
            "summary": "",
            "url": "classes/Sheet-Import.html#property_spreadsheetID"
        },                {
            "fqsen": "\\Sheet_Import\u003A\u003A\u0024sheetRange",
            "name": "sheetRange",
            "summary": "",
            "url": "classes/Sheet-Import.html#property_sheetRange"
        },                {
            "fqsen": "\\Sheet_Import\u003A\u003A\u0024credentialsPath",
            "name": "credentialsPath",
            "summary": "",
            "url": "classes/Sheet-Import.html#property_credentialsPath"
        },                {
            "fqsen": "\\BULK_IMPORT\\Inc\\Traits\\Program_Logs",
            "name": "Program_Logs",
            "summary": "",
            "url": "classes/BULK-IMPORT-Inc-Traits-Program-Logs.html"
        },                {
            "fqsen": "\\BULK_IMPORT\\Inc\\Traits\\Program_Logs\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "Protected\u0020class\u0020constructor\u0020to\u0020prevent\u0020direct\u0020object\u0020creation",
            "url": "classes/BULK-IMPORT-Inc-Traits-Program-Logs.html#method___construct"
        },                {
            "fqsen": "\\BULK_IMPORT\\Inc\\Traits\\Program_Logs\u003A\u003Aput_program_logs\u0028\u0029",
            "name": "put_program_logs",
            "summary": "",
            "url": "classes/BULK-IMPORT-Inc-Traits-Program-Logs.html#method_put_program_logs"
        },                {
            "fqsen": "\\BULK_IMPORT\\Inc\\Traits\\Singleton",
            "name": "Singleton",
            "summary": "",
            "url": "classes/BULK-IMPORT-Inc-Traits-Singleton.html"
        },                {
            "fqsen": "\\BULK_IMPORT\\Inc\\Traits\\Singleton\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "Protected\u0020class\u0020constructor\u0020to\u0020prevent\u0020direct\u0020object\u0020creation",
            "url": "classes/BULK-IMPORT-Inc-Traits-Singleton.html#method___construct"
        },                {
            "fqsen": "\\BULK_IMPORT\\Inc\\Traits\\Singleton\u003A\u003A__clone\u0028\u0029",
            "name": "__clone",
            "summary": "Prevent\u0020object\u0020cloning",
            "url": "classes/BULK-IMPORT-Inc-Traits-Singleton.html#method___clone"
        },                {
            "fqsen": "\\BULK_IMPORT\\Inc\\Traits\\Singleton\u003A\u003Aget_instance\u0028\u0029",
            "name": "get_instance",
            "summary": "This\u0020method\u0020returns\u0020new\u0020or\u0020existing\u0020Singleton\u0020instance\nof\u0020the\u0020class\u0020for\u0020which\u0020it\u0020is\u0020called.\u0020This\u0020method\u0020is\u0020set\nas\u0020final\u0020intentionally,\u0020it\u0020is\u0020not\u0020meant\u0020to\u0020be\u0020overridden.",
            "url": "classes/BULK-IMPORT-Inc-Traits-Singleton.html#method_get_instance"
        },                {
            "fqsen": "\\",
            "name": "\\",
            "summary": "",
            "url": "namespaces/default.html"
        },                {
            "fqsen": "\\BULK_IMPORT\\Inc",
            "name": "Inc",
            "summary": "",
            "url": "namespaces/bulk-import-inc.html"
        },                {
            "fqsen": "\\BULK_IMPORT",
            "name": "BULK_IMPORT",
            "summary": "",
            "url": "namespaces/bulk-import.html"
        },                {
            "fqsen": "\\BULK_IMPORT\\Inc\\Helpers",
            "name": "Helpers",
            "summary": "",
            "url": "namespaces/bulk-import-inc-helpers.html"
        },                {
            "fqsen": "\\BULK_IMPORT\\Inc\\Traits",
            "name": "Traits",
            "summary": "",
            "url": "namespaces/bulk-import-inc-traits.html"
        }            ]
);
